# Liste des aéroports (code IATA et nom complet)
aeroports= [
    ("AAL", "Aalborg Airport"),
    ("AAR", "Aarhus Airport"),
    ("ABA", "Abakan International Airport"),
    ("ABZ", "Aberdeen Airport"),
    ("PSR", "Abruzzo Airport"),
    ("ADB", "Adnan Menderes Airport"),
    ("PVK", "Aktion National Airport"),
    ("AEY", "Akureyri Airport"),
    ("NUE", "Albrecht Dürer Airport"),
    ("ILD", "Alguaire Airport"),
    ("ALC", "Alicante Airport"),
    ("LEI", "Almería International Airport"),
    ("LCG", "Alvedro Airport"),
    ("UGA", "Ambrolauri Airport"),
    ("AMS", "Amsterdam Airport Schiphol"),
    ("AAQ", "Anapa Airport"),
    ("AOI", "Ancona Airport"),
    ("AYT", "Antalya Airport"),
    ("ANR", "Antwerp International Airport"),
    ("OVD", "Asturias Airport"),
    ("IST", "Atatürk International Airport"),
    ("ATH", "Athens International Airport"),
    ("UUD", "Baikal International Airport"),
    ("BNX", "Banja Luka International Airport"),
    ("BCN", "Barcelona Airport"),
    ("BAX", "Barnaul Airport"),
    ("BSL", "Basel-Mulhouse-Freiburg Airport"),
    ("BUS", "Batumi International Airport"),
    ("BVA", "Beauvais-Tillé Airport"),
    ("NBC", "Begishevo Airport"),
    ("BYJ", "Beja Airport"),
    ("BFS", "Belfast International Airport"),
    ("EGO", "Belgorod International Airport"),
    ("BEG", "Belgrade Nikola Tesla Airport"),
    ("LIG", "Bellegarde Airport"),
    ("BGO", "Bergen Airport"),
    ("EGC", "Bergerac-Roumanière Airport"),
    ("BER", "Berlin Brandenburg Airport"),
    ("SXF", "Berlin Schönefeld Airport"),
    ("TXL", "Berlin Tegel Airport"),
    ("BRN", "Bern-Belp Airport"),
    ("OGZ", "Beslan Airport"),
    ("PIS", "Biard Airport"),
    ("BIQ", "Biarritz Airport"),
    ("BLL", "Billund Airport"),
    ("BHX", "Birmingham International Airport"),
    ("TLS", "Blagnac Airport"),
    ("BOO", "Bodø Airport"),
    ("TOF", "Bogashevo Airport"),
    ("BLQ", "Bologna Airport"),
    ("KBP", "Boryspil International Airport"),
    ("BOH", "Bournemouth Airport"),
    ("EBU", "Bouthéon Airport"),
    ("BTK", "Bratsk Airport"),
    ("BRE", "Bremen Airport"),
    ("VBS", "Brescia Airport"),
    ("BES", "Brest Bretagne Airport"),
    ("BDS", "Brindisi Airport"),
    ("BRS", "Bristol Airport"),
    ("BRQ", "Brno-Tuřany Airport"),
    ("BRU", "Brussels Airport"),
    ("CRL", "Brussels South Charleroi Airport"),
    ("BZK", "Bryansk International Airport"),
    ("BUD", "Budapest Ferenc Liszt International Airport"),
    ("BOJ", "Burgas Airport"),
    ("BZG", "Bydgoszcz Ignacy Jan Paderewski Airport"),
    ("BZR", "Béziers Cap d'Agde Airport"),
    ("CAG", "Cagliari Airport"),
    ("AJA", "Campo dell'Oro Airport"),
    ("NAP", "Capodichino Airport"),
    ("CWL", "Cardiff Airport"),
    ("TRN", "Caselle Airport"),
    ("CMF", "Chambéry-Savoie Airport"),
    ("CHQ", "Chania International Airport"),
    ("CDG", "Charles de Gaulle Airport"),
    ("CSY", "Cheboksary Airport"),
    ("CEK", "Chelyabinsk Airport"),
    ("CEE", "Cherepovets Airport"),
    ("CWC", "Chernivtsi International Airport"),
    ("JKH", "Chios Island National Airport"),
    ("KIV", "Chişinău International Airport"),
    ("XCR", "Châlons Vatry Airport"),
    ("LDY", "City of Derry Airport"),
    ("CLJ", "Cluj-Napoca International Airport"),
    ("CGN", "Cologne"),
    ("CPH", "Copenhagen Airport"),
    ("WRO", "Copernicus Airport Wrocław"),
    ("ORK", "Cork Airport"),
    ("OLB", "Costa Smeralda Airport"),
    ("GOA", "Cristoforo Colombo Airport"),
    ("CUF", "Cuneo Levaldigi Airport"),
    ("NCE", "Côte d'Azur Airport"),
    ("DLM", "Dalaman Airport"),
    ("DEB", "Debrecen International Airport"),
    ("DNK", "Dnipropetrovsk International Airport"),
    ("DME", "Domodedovo International Airport"),
    ("DOK", "Donetsk Airport"),
    ("DTM", "Dortmund Airport"),
    ("DUB", "Dublin Airport"),
    ("DBV", "Dubrovnik Airport"),
    ("MME", "Durham Tees Valley Airport"),
    ("DUS", "Düsseldorf Airport"),
    ("EMA", "East Midlands Airport"),
    ("EDI", "Edinburgh Airport"),
    ("EIN", "Eindhoven Airport"),
    ("ESL", "Elista Airport"),
    ("ECN", "Ercan International Airport"),
    ("MLX", "Erhaç Airport"),
    ("ASR", "Erkilet Airport"),
    ("ESB", "Esenboğa International Airport"),
    ("MLH", "EuroAirport Basel Mulhouse Freiburg"),
    ("BSL", "EuroAirport Basel Mulhouse Freiburg"),
    ("EAP", "EuroAirport Basel Mulhouse Freiburg"),
    ("BSL", "EuroAirport Basel Mulhouse Freiburg"),
    ("EXT", "Exeter International Airport"),
    ("FAO", "Faro Airport"),
    ("RMI", "Federico Fellini Airport"),
    ("AHO", "Fertilia Airport"),
    ("FSC", "Figari Sud-Corse Airport"),
    ("LUX", "Findel Airport"),
    ("CTA", "Fontanarossa Airport"),
    ("OPO", "Francisco Sá Carneiro Airport"),
    ("ZAG", "Franjo Tuđman Airport"),
    ("FRA", "Frankfurt Airport"),
    ("HHN", "Frankfurt-Hahn Airport"),
    ("FDH", "Friedrichshafen Airport"),
    ("TRS", "Friuli Venezia Giulia Airport"),
    ("WAW", "Frédéric Chopin Airport"),
    ("FUE", "Fuerteventura Airport"),
    ("PSA", "Galileo Galilei Airport"),
    ("KVD", "Ganja International Airport"),
    ("FNI", "Garons Airport"),
    ("LGW", "Gatwick Airport"),
    ("GDN", "Gdańsk Lech Wałęsa Airport"),
    ("GVA", "Geneva International Airport"),
    ("BHD", "George Best Belfast City Airport"),
    ("GRO", "Girona-Costa Brava Airport"),
    ("GLA", "Glasgow International Airport"),
    ("PIK", "Glasgow Prestwick Airport"),
    ("GME", "Gomel Airport"),
    ("GML", "Gostomel Airport"),
    ("GSE", "Gothenburg City Airport"),
    ("LPA", "Gran Canaria Airport"),
    ("GRX", "Granada Airport"),
    ("GRZ", "Graz Airport"),
    ("GNB", "Grenoble-Isère Airport"),
    ("GRQ", "Groningen Airport Eelde"),
    ("GRV", "Grozny Airport"),
    ("GCI", "Guernsey Airport"),
    ("QGY", "Győr-Pér International Airport"),
    ("GOT", "Göteborg Landvetter Airport"),
    ("HAM", "Hamburg Airport"),
    ("HAU", "Haugesund Airport"),
    ("LHR", "Heathrow Airport"),
    ("HEL", "Helsinki-Vantaa Airport"),
    ("OTP", "Henri Coanda International Airport"),
    ("HER", "Heraklion International Airport"),
    ("GYD", "Heydar Aliyev International Airport"),
    ("GNA", "Hrodna Airport"),
    ("HSK", "Huesca-Pirineos Airport"),
    ("LIS", "Humberto Delgado Airport"),
    ("TLN", "Hyères Le Palyvestre Airport"),
    ("SOB", "Hévíz-Balaton Airport"),
    ("IAS", "Iași International Airport"),
    ("IBZ", "Ibiza Airport"),
    ("BQS", "Ignatyevo Airport"),
    ("INN", "Innsbruck Airport"),
    ("INV", "Inverness Airport"),
    ("CFU", "Ioannis Kapodistrias Airport"),
    ("NOC", "Ireland West Airport Knock"),
    ("IKT", "Irkutsk Airport"),
    ("IOM", "Isle of Man Airport"),
    ("IFO", "Ivano-Frankivsk International Airport"),
    ("XRY", "Jerez Airport"),
    ("JER", "Jersey Airport"),
    ("KRK", "John Paul II International Airport Kraków-Balice"),
    ("PDL", "João Paulo II Airport"),
    ("HTA", "Kadala Airport"),
    ("KLX", "Kalamata International Airport"),
    ("NAV", "Kapadokya Airport"),
    ("KLV", "Karlovy Vary Airport"),
    ("FKB", "Karlsruhe"),
    ("AOK", "Karpathos Island National Airport"),
    ("KTW", "Katowice International Airport"),
    ("KUN", "Kaunas Airport"),
    ("KVA", "Kavala International Airport"),
    ("KZN", "Kazan Airport"),
    ("EFL", "Kefalonia Island International Airport"),
    ("KEF", "Keflavik International Airport"),
    ("KIR", "Kerry Airport"),
    ("KHV", "Khabarovsk Novy Airport"),
    ("HRK", "Kharkiv International Airport"),
    ("KGD", "Khrabrovo Airport"),
    ("KTT", "Kittilä Airport"),
    ("KLU", "Klagenfurt Airport"),
    ("SVX", "Koltsovo International Airport"),
    ("KXK", "Komsomolsk-on-Amur Airport"),
    ("KYA", "Konya Airport"),
    ("KGS", "Kos Island International Airport"),
    ("KSC", "Košice International Airport"),
    ("KRS", "Kristiansand Airport"),
    ("KSU", "Kristiansund Airport"),
    ("KWG", "Kryvyi Rih International Airport"),
    ("KUO", "Kuopio Airport"),
    ("URS", "Kursk Vostochny Airport"),
    ("KUT", "Kutaisi International Airport"),
    ("KAO", "Kuusamo Airport"),
    ("IEV", "Kyiv Zhuliany International Airport"),
    ("SPC", "La Palma Airport"),
    ("SUF", "Lamezia Terme Airport"),
    ("HAJ", "Langenhagen Airport"),
    ("LLK", "Lankaran International Airport"),
    ("ACE", "Lanzarote Airport"),
    ("LPP", "Lappeenranta Airport"),
    ("LCA", "Larnaca International Airport"),
    ("LBA", "Leeds Bradford International Airport"),
    ("LEJ", "Leipzig"),
    ("TLL", "Lennart Meri Tallinn Airport"),
    ("FCO", "Leonardo da Vinci-Fiumicino Airport"),
    ("OSR", "Leoš Janáček Ostrava Airport"),
    ("LIL", "Lille Lesquin Airport"),
    ("LIN", "Linate Airport"),
    ("LNZ", "Linz Airport"),
    ("LPL", "Liverpool John Lennon Airport"),
    ("LGG", "Liège Airport"),
    ("LJU", "Ljubljana Jože Pučnik Airport"),
    ("PGF", "Llabanère Airport"),
    ("LCY", "London City Airport"),
    ("LUZ", "Lublin Airport"),
    ("VSG", "Luhansk International Airport"),
    ("LLA", "Luleå Airport"),
    ("LTN", "Luton Airport"),
    ("LWO", "Lviv Danylo Halytskyi International Airport"),
    ("LBC", "Lübeck Airport"),
    ("BTS", "M. R. Štefánik Airport"),
    ("MST", "Maastricht-Aachen Airport"),
    ("FNC", "Madeira Airport"),
    ("MAD", "Madrid-Barajas Airport"),
    ("MQF", "Magnitogorsk International Airport"),
    ("MMX", "Malmö Airport"),
    ("MXP", "Malpensa Airport"),
    ("MLA", "Malta International Airport"),
    ("MAN", "Manchester Airport"),
    ("RDZ", "Marcillac Airport"),
    ("MBX", "Maribor Edvard Rusjan Airport"),
    ("MHQ", "Mariehamn Airport"),
    ("FMM", "Memmingen Airport"),
    ("MAH", "Menorca Airport"),
    ("CND", "Mihail Kogălniceanu International Airport"),
    ("BJV", "Milas-Bodrum Airport"),
    ("MRV", "Mineralnye Vody Airport"),
    ("MSQ", "Minsk International Airport"),
    ("WMI", "Modlin Airport"),
    ("RYG", "Moss Airport"),
    ("OMO", "Mostar International Airport"),
    ("MUC", "Munich Airport"),
    ("MJV", "Murcia-San Javier Airport"),
    ("MMK", "Murmansk Airport"),
    ("NLV", "Mykolaiv International Airport"),
    ("JMK", "Mykonos Island National Airport"),
    ("MJT", "Mytilene International Airport"),
    ("AGP", "Málaga Airport"),
    ("BOD", "Mérignac Airport"),
    ("NAJ", "Nakhchivan Airport"),
    ("NAL", "Nalchik Airport"),
    ("NTE", "Nantes Atlantique Airport"),
    ("ASF", "Narimanovo Airport"),
    ("UGS", "Natakhtari Airfield"),
    ("VOL", "Nea Anchialos National Airport"),
    ("NCL", "Newcastle Airport"),
    ("NQY", "Newquay Cornwall Airport"),
    ("NJC", "Nizhnevartovsk Airport"),
    ("INI", "Niš Constantine the Great Airport"),
    ("NRK", "Norrköping Airport"),
    ("GIB", "North Front Airport"),
    ("NWI", "Norwich International Airport"),
    ("ODS", "Odessa International Airport"),
    ("OHD", "Ohrid St. Paul the Apostle Airport"),
    ("OMS", "Omsk Tsentralny Airport"),
    ("OMR", "Oradea International Airport"),
    ("REN", "Orenburg Tsentralny Airport"),
    ("BGY", "Orio al Serio Airport"),
    ("ORY", "Orly Airport"),
    ("OSW", "Orsk Airport"),
    ("OSI", "Osijek Airport"),
    ("OSL", "Oslo Airport-Gardermoen"),
    ("OST", "Ostend-Bruges International Airport"),
    ("OUL", "Oulu Airport"),
    ("GZT", "Oğuzeli Airport"),
    ("PLQ", "Palanga International Airport"),
    ("PMO", "Palermo Airport"),
    ("BRI", "Palese Airport"),
    ("PMI", "Palma de Mallorca Airport"),
    ("PFO", "Paphos International Airport"),
    ("PED", "Pardubice Airport"),
    ("KRR", "Pashkovsky Airport"),
    ("FLR", "Peretola Airport"),
    ("PEE", "Perm International Airport"),
    ("PES", "Petrozavodsk Airport"),
    ("PZY", "Piešťany Airport"),
    ("DNR", "Pleurtuit Airport"),
    ("PDV", "Plovdiv Airport"),
    ("TGD", "Podgorica Airport"),
    ("TAT", "Poprad-Tatry Airport"),
    ("BIA", "Poretta Airport"),
    ("PXO", "Porto Santo Airport"),
    ("POW", "Portorož Airport"),
    ("POZ", "Poznań Ławica Airport"),
    ("PRG", "Prague Václav Havel Airport"),
    ("PRN", "Pristina International Airport"),
    ("MRS", "Provence Airport"),
    ("PVS", "Provideniya Bay Airport"),
    ("PKV", "Pskov Airport"),
    ("PUY", "Pula Airport"),
    ("LED", "Pulkovo Airport"),
    ("QPJ", "Pécs-Pogány International Airport"),
    ("GBB", "Qabala International Airport"),
    ("UGM", "Queen Tamar Airport"),
    ("REU", "Reus Airport"),
    ("RKV", "Reykjavik Airport"),
    ("RHO", "Rhodes International Airport"),
    ("RIX", "Riga International Airport"),
    ("RJK", "Rijeka Airport"),
    ("DSA", "Robin Hood Airport Doncaster Sheffield"),
    ("CIA", "Rome Ciampino Airport"),
    ("TJM", "Roshchino International Airport"),
    ("ROV", "Rostov-na-Donu Airport"),
    ("RTM", "Rotterdam The Hague Airport"),
    ("RVN", "Rovaniemi Airport"),
    ("RZE", "Rzeszów-Jasionka Airport"),
    ("SAW", "Sabiha Gökçen International Airport"),
    ("LYS", "Saint-Exupéry Airport"),
    ("CCF", "Salvaza Airport"),
    ("SZG", "Salzburg Airport"),
    ("KUF", "Samara Kurumoch Airport"),
    ("SMI", "Samos International Airport"),
    ("SZF", "Samsun-Çarşamba Airport"),
    ("PEG", "San Egidio Airport"),
    ("TRF", "Sandefjord Airport"),
    ("SDR", "Santander Airport"),
    ("SCQ", "Santiago de Compostela Airport"),
    ("JTR", "Santorini National Airport"),
    ("SJJ", "Sarajevo International Airport"),
    ("RTW", "Saratov Tsentralny Airport"),
    ("SVQ", "Seville Airport"),
    ("SNN", "Shannon Airport"),
    ("SVO", "Sheremetyevo International Airport"),
    ("LWN", "Shirak Airport"),
    ("SBZ", "Sibiu International Airport"),
    ("SIP", "Simferopol International Airport"),
    ("JSI", "Skiathos Island National Airport"),
    ("SKP", "Skopje Alexander the Great Airport"),
    ("SKU", "Skyros Island National Airport"),
    ("SLD", "Sliač Airport"),
    ("AER", "Sochi International Airport"),
    ("SOF", "Sofia Airport"),
    ("GDX", "Sokol Airport"),
    ("SOU", "Southampton Airport"),
    ("SEN", "Southend Airport"),
    ("NOZ", "Spichenkovo Airport"),
    ("SPU", "Split Airport"),
    ("ACH", "St. Gallen-Altenrhein Airport"),
    ("STN", "Stansted Airport"),
    ("SVG", "Stavanger Airport"),
    ("STW", "Stavropol Shpakovskoye Airport"),
    ("ARN", "Stockholm-Arlanda Airport"),
    ("BMA", "Stockholm-Bromma Airport"),
    ("NYO", "Stockholm-Skavsta Airport"),
    ("VST", "Stockholm-Västerås Airport"),
    ("SXB", "Strasbourg Airport"),
    ("GOJ", "Strigino Airport"),
    ("STR", "Stuttgart Airport"),
    ("SUI", "Sukhumi Babushara Airport"),
    ("SGC", "Surgut International Airport"),
    ("SCW", "Syktyvkar Airport"),
    ("SZZ", "Szczecin-Goleniów Solidarność Airport"),
    ("ARH", "Talagi Airport"),
    ("TMP", "Tampere-Pirkkala Airport"),
    ("TAY", "Tartu Airport"),
    ("TBS", "Tbilisi International Airport"),
    ("TFN", "Tenerife North Airport"),
    ("TFS", "Tenerife South Airport"),
    ("TER", "Terceira Airport"),
    ("SKG", "Thessaloniki International Airport"),
    ("TIA", "Tirana International Airport Nënë Tereza"),
    ("TIV", "Tivat Airport"),
    ("OVB", "Tolmachevo Airport"),
    ("TUF", "Tours Loire Valley Airport"),
    ("TZX", "Trabzon Airport"),
    ("TSR", "Traian Vuia International Airport"),
    ("TOS", "Tromsø Airport"),
    ("TRD", "Trondheim Airport"),
    ("IAR", "Tunoshna Airport"),
    ("TKU", "Turku Airport"),
    ("TZL", "Tuzla International Airport"),
    ("UFA", "Ufa International Airport"),
    ("DYR", "Ugolny Airport"),
    ("ULY", "Ulyanovsk Vostochny Airport"),
    ("UME", "Umeå Airport"),
    ("MCX", "Uytash Airport"),
    ("PUF", "Uzein Airport"),
    ("VAA", "Vaasa Airport"),
    ("VLC", "Valencia Airport"),
    ("VLL", "Valladolid Airport"),
    ("VAR", "Varna Airport"),
    ("VCE", "Venice Marco Polo Airport"),
    ("VNT", "Ventspils International Airport"),
    ("VRN", "Verona Airport"),
    ("VIE", "Vienna International Airport"),
    ("VNO", "Vilnius International Airport"),
    ("TPS", "Vincenzo Florio Airport"),
    ("VBY", "Visby Airport"),
    ("VVO", "Vladivostok International Airport"),
    ("VKO", "Vnukovo Airport"),
    ("VOG", "Volgograd International Airport"),
    ("VOZ", "Voronezh International Airport"),
    ("FAE", "Vágar Airport"),
    ("VXO", "Växjö Airport"),
    ("NRN", "Weeze Airport"),
    ("YKS", "Yakutsk Airport"),
    ("PKC", "Yelizovo Airport"),
    ("KJA", "Yemelyanovo International Airport"),
    ("YEI", "Yenişehir Airport"),
    ("UUS", "Yuzhno-Sakhalinsk Airport"),
    ("ZAD", "Zadar Airport"),
    ("KZR", "Zafer Airport"),
    ("ZTH", "Zakynthos International Airport"),
    ("OZH", "Zaporizhia International Airport"),
    ("ZAZ", "Zaragoza Airport"),
    ("ONQ", "Zonguldak Airport"),
    ("ZRH", "Zurich Airport"),
    ("EVN", "Zvartnots International Airport"),
    ("AES", "Ålesund Airport"),
    ("OSD", "Åre Östersund Airport"),
    ("LRH", "Île de Ré Airport"),
    ("LCJ", "Łódź Władysław Reymont Airport"),
    ("ADA", "Şakirpaşa Airport"),
    ("SQQ", "Šiauliai International Airport"),
    ("ILZ", "Žilina Airport"),
]